#!/usr/bin/env bash
# generate-effective-gates.sh
# Compiles .sweetclaude/state/effective-gates.yaml from config/mode-gates.yaml
# and the project's sweetclaude.yaml. Run at mode setup and on every mode shift.
#
# Usage: PROJECT_DIR=/path/to/project bash generate-effective-gates.sh
# Defaults PROJECT_DIR to current working directory.

set -euo pipefail

PROJECT_DIR="${PROJECT_DIR:-$(pwd)}"
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CONFIG="$REPO_ROOT/config/mode-gates.yaml"
SWEETCLAUDE_YAML="$PROJECT_DIR/.sweetclaude/state/sweetclaude.yaml"
OUTPUT="$PROJECT_DIR/.sweetclaude/state/effective-gates.yaml"

if [ ! -f "$SWEETCLAUDE_YAML" ]; then
    echo "ERROR: $SWEETCLAUDE_YAML not found" >&2; exit 1
fi
if [ ! -f "$CONFIG" ]; then
    echo "ERROR: $CONFIG not found" >&2; exit 1
fi

python3 - "$CONFIG" "$SWEETCLAUDE_YAML" "$OUTPUT" << 'PYEOF'
import sys, yaml
from datetime import datetime, timezone

config_path, sc_path, out_path = sys.argv[1], sys.argv[2], sys.argv[3]

with open(config_path) as f:
    config = yaml.safe_load(f)

with open(sc_path) as f:
    project = yaml.safe_load(f) or {}

mode = project.get('mode', 'flow')
mc = config.get('mode_defaults', {}).get(mode)
if mc is None:
    print(f"ERROR: unknown mode '{mode}'", file=sys.stderr)
    sys.exit(1)

wip_limit = project['wip_limit'] if 'wip_limit' in project else mc.get('wip_limit')
cycle_weeks = project['cycle_duration_weeks'] if 'cycle_duration_weeks' in project else mc.get('cycle_duration_weeks')

effective = {
    'schema_version': 1,
    'generated_at': datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ'),
    'mode': mode,
    'default_tdd_level': mc['default_tdd_level'],
    'blocked_skills': mc.get('blocked_skills', []),
    'gates': mc.get('gates', []),
}
if wip_limit is not None:
    effective['wip_limit'] = wip_limit
if cycle_weeks is not None:
    effective['cycle_duration_weeks'] = cycle_weeks

with open(out_path, 'w') as f:
    f.write('# .sweetclaude/state/effective-gates.yaml\n')
    f.write('# Generated by generate-effective-gates — do not edit manually\n')
    yaml.dump(effective, f, default_flow_style=False, sort_keys=False)

print(f"Generated {out_path} for mode '{mode}'")
PYEOF
